mod ast;
mod lexer;
mod parser;
mod token;
mod symbol;
mod codegen;
mod optimizer;
mod peephole;
mod liveness;
mod ir;
mod typecheck;

use lexer::Lexer;
use parser::Parser;
use std::{env, fs, process};
use token::Token;
use symbol::build_symbol_table;
use crate::ast::Stmt;
use codegen::CodeGen;
use optimizer::AstOptimizer;
use peephole::PeepholeOptimizer;
use ir::{IrBuilder, licm_optimize};
use typecheck::{infer_expression_type, Type, TypeChecker};
use std::fs::File;
use std::io::Write;



fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: cargo run -- <source_file>");
        return;
    }

    let file_path = &args[1];

    let source = fs::read_to_string(file_path).expect("Failed to read source file");

    let mut lexer = Lexer::new(&source);

    let mut tokens: Vec<Token> = Vec::new();

    loop {
        let token = lexer.next_token();
        tokens.push(token);

        if tokens[tokens.len() - 1] == Token::Eof {
            break;
        }
    }

    println!("{:#?}", tokens);

    let mut parser = Parser::new(tokens);
    let program = parser.parse_program();

    println!("\n=== PHASE 1: AST Optimization (Constant Folding + Dead Code) ===");
    let ast_optimizer = AstOptimizer::new();
    let optimized_program = ast_optimizer.optimize_program(&program);

    println!("\n=== PHASE 2: Type Checking ===");
    let mut type_checker = TypeChecker::new();
    if !type_checker.check_program(&optimized_program) {
        process::exit(1);
    }
    let mut globals = type_checker.get_globals().clone();
    println!("  Type checking passed");

    println!("\n=== PHASE 3: IR Building with CSE & Strength Reduction ===");
    let mut ir_builder = IrBuilder::new(globals.clone());
    let ir_program = ir_builder.build_program(&optimized_program);
    println!("  Temporaries created: {}", ir_builder.temps.len());

    println!("\n=== PHASE 4: Loop Invariant Code Motion ===");
    let mut ir_program = ir_program;
    licm_optimize(&mut ir_program, &ir_builder);
    println!("  IR statements after LICM: {}", ir_program.stmts.len());

    println!("\n=== PHASE 5: IR to AST Conversion ===");
    let ir_optimized_program = ir_builder.ir_to_ast(&ir_program);
    println!("  AST statements after IR phase: {}", ir_optimized_program.len());

    // Infer types for IR-generated temps so codegen knows string temp types
    for stmt in &ir_optimized_program {
        if let Stmt::Assign { name, value } = stmt {
            if name.starts_with("__tmp") && !globals.contains_key(name) {
                let t = infer_expression_type(value, &globals);
                if t != Type::Unknown {
                    globals.insert(name.clone(), t);
                }
            }
        }
    }

    println!("\n=== PHASE 6: Symbol Table Building ===");
    let symbols = build_symbol_table(&ir_optimized_program);

    println!("\n=== PHASE 7: Code Generation ===");
    let bytecode = CodeGen::new(globals.clone()).generate(&ir_optimized_program, &symbols);

    println!("\n=== PHASE 8: Peephole Optimization ===");
    let peephole_optimizer = PeepholeOptimizer::new();
    let optimized_bytecode = peephole_optimizer.optimize(&bytecode);
    
    println!("Original bytecode size: {} bytes", bytecode.len());
    println!("Optimized bytecode size: {} bytes", optimized_bytecode.len());
    println!("Saved: {} bytes ({:.1}%)", 
        bytecode.len() - optimized_bytecode.len(),
        (bytecode.len() - optimized_bytecode.len()) as f32 / bytecode.len() as f32 * 100.0
    );

    println!("\nGenerated bytecode:");
    println!("{:?}", optimized_bytecode);

    let mut file = File::create("test.by").expect("Failed to create test.by");

    let mut i = 0;
    while i < optimized_bytecode.len() {
        let opcode = optimized_bytecode[i];
        write!(file, "0x{:02X}", opcode).unwrap();

        // Instructions with 1-byte operand
        match opcode {
            0x01 | 0x08 | 0x20 | 0x21 | 0x40 | 0x41 | 0x50 | 0x60 => {
                if i + 1 < optimized_bytecode.len() {
                    let operand = optimized_bytecode[i + 1];
                    write!(file, ", {},\n", operand).unwrap();
                    i += 2;
                } else {
                    write!(file, ",\n").unwrap();
                    i += 1;
                }
            }

            // Instructions without operands
            _ => {
                write!(file, ",\n").unwrap();
                i += 1;
            }
        }
    }

    println!("{:#?}", ir_optimized_program);


    println!("Bytecode written to test.by");

}
