mod ast;
mod lexer;
mod parser;
mod token;
mod symbol;
mod codegen;

use lexer::Lexer;
use parser::Parser;
use std::{env, fs};
use token::Token;
use symbol::build_symbol_table;
use codegen::CodeGen;
use std::fs::File;
use std::io::Write;



fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: cargo run -- <source_file>");
        return;
    }

    let file_path = &args[1];

    let source = fs::read_to_string(file_path).expect("Failed to read source file");

    let mut lexer = Lexer::new(&source);

    let mut tokens: Vec<Token> = Vec::new();

    loop {
        let token = lexer.next_token();
        tokens.push(token);

        if tokens[tokens.len() - 1] == Token::Eof {
            break;
        }
    }

    let mut parser = Parser::new(tokens);
    let program = parser.parse_program();

    let symbols = build_symbol_table(&program);

    let bytecode = CodeGen::new().generate(&program, &symbols);

    println!("\nGenerated bytecode:");
    println!("{:?}", bytecode);

    let mut file = File::create("test.by").expect("Failed to create test.by");

    let mut i = 0;
    while i < bytecode.len() {
        let opcode = bytecode[i];
        write!(file, "0x{:02X}", opcode).unwrap();

        // Instructions with 1-byte operand
        match opcode {
            0x01 | 0x20 | 0x21 | 0x40 | 0x41 => {
                let operand = bytecode[i + 1];
                write!(file, ", {},\n", operand).unwrap();
                i += 2;
            }

            // Instructions without operands
            _ => {
                write!(file, ",\n").unwrap();
                i += 1;
            }
        }
    }

    println!("Bytecode written to test.by");

}
